language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
  - npm test
  - npm run build
  # - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

branches:
  only:
    - master
