export const FOUND_BAD_WORD = "FOUND_BAD_WORD";
export const DATA_LOADED = "DATA_LOADED";


// Login Logout Action Types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SET_USER_OBJECT = "SET_USER_OBJECT";

// Signup Action Types
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// Task Action Types
export const NEW_TASK_REQUESTED = "NEW_TASK_REQUESTED";
export const NEW_TASK_SUCCESS = "NEW_TASK_SUCCESS";

export const GET_TASKS_REQUESTED = "GET_TASKS_REQUESTED";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";

export const TASK_DETAILS_REQUESTED = "TASK_DETAILS_REQUESTED";
export const TASK_DETAILS_SUCCESS = "TASK_DETAILS_SUCCESS";

export const TASK_UPDATE_REQUESTED = "TASK_UPDATE_REQUESTED";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";

export const TASK_DELETE_REQUESTED = "TASK_DELETE_REQUESTED";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";


// Api action Types
export const API_ERRORED = "API_ERRORED";

